language: scala
dist: xenial

scala:
  - 2.13.0

jdk:
  - openjdk11

jobs:
  include:
    - env: TEST="scalafmt"
      script: sbt ++$TRAVIS_SCALA_VERSION check
    - env: TEST="compilation"
      script: sbt ++$TRAVIS_SCALA_VERSION compile coverage test
      after_success:
        - sbt ++$TRAVIS_SCALA_VERSION coverageReport
        - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
        - sbt ++$TRAVIS_SCALA_VERSION codacyCoverage

cache:
  directories:
    - "$HOME/.coursier/cache"
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot"

before_cache:
  - cleanup_cache