language: scala
dist: xenial

scala:
  - 2.13.0

jdk:
  - openjdk8

services:
  - postgresql

before_script:
  - psql -c 'create database test;' -U postgres

jobs:
  include:
    - env: TEST="scalafmt"
      script: sbt ++$TRAVIS_SCALA_VERSION check
    - env: TEST="compilation"
      script: sbt ++$TRAVIS_SCALA_VERSION compile test

cache:
  directories:
    - "$HOME/.coursier/cache"
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot"

before_cache:
  - cleanup_cache