addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.3.25")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.0.3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.7")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"       % "1.6.0")
addSbtPlugin("com.github.mwz"            % "sbt-sonar"           % "2.0.0")
