addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.4.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.0.6")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.8")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"       % "1.6.0")
addSbtPlugin("com.github.mwz"            % "sbt-sonar"           % "2.0.0")
addSbtPlugin("com.codacy"                % "sbt-codacy-coverage" % "3.0.3")
