name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v10
      
    - name: Run tests
      run: sbt test
    - name: Run Format test
      run: sbt check
